common:
    resource: "@CommonBundle/Controller/"
    type:     annotation
    prefix:   /api

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /api/user
#    condition: "request.isXmlHttpRequest()"