<?php

namespace App\Constant;

class ApiCodes {
	
	// ERRORS
	CONST COMMON_ERROR								= 1;
	CONST INVALID_EMAIL								= 2;
	CONST EMAIL_EXISTS								= 3;
	CONST USER_PASS_NOT_MATCH						= 4;
	CONST UNAUTHORIZED								= 5;
	CONST USER_NOT_CONFIRMED						= 6;
	CONST EMAIL_NOT_EXISTS							= 7;
	CONST CONFIRMATION_EMAIL_ALREADY_SENT			= 9;
	CONST CONFIRMATION_HASH_NOT_FOUND				= 10;
	CONST FORGOTTEN_EMAIL_ALREADY_SENT				= 13;
	CONST FORGOTTEN_HASH_NOT_EXISTS					= 14;
	CONST NEW_PASSWORD_SENT_FAIL					= 15;
	CONST USER_CREATED								= 17;
	CONST USER_UPDATED								= 18;

	// SUCCESS
	const REGIST_CONFIRMATION_SENT					= 8;
	const CONFIRMATION_SUCCESS						= 11;
	const FORGOTTEN_PASSWORD_SENT					= 12;
	const NEW_PASSWORD_RESET						= 16;
	const CHANGE_ROLE_SUCCESS						= 19;
	const USER_LOGGED								= 20;
}
