services:
    CommonBundle\Services\Helpers:
        public: true
        arguments: 
            $manager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'
            
    CommonBundle\Services\JwtAuth:
        public: true
        arguments: 
            $manager: '@doctrine.orm.entity_manager'
            $helpers: '@CommonBundle\Services\Helpers'